"""activities applications likes

Revision ID: 3c848a257a7d
Revises: cd4f3e4e4625
Create Date: 2026-10-02 10:26:22.464770

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c848a257a7d"
down_revision: str | Sequence[str] | None = "cd4f3e4e4625"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("subtitle", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("region_code", sa.String(length=10), nullable=False),
        sa.Column("place", sa.String(length=100), nullable=False),
        sa.Column("schedule_text", sa.String(length=60), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_kind", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('culture', 'health', 'learning')", name=op.f("ck_activities_category")
        ),
        sa.CheckConstraint("capacity > 0", name=op.f("ck_activities_capacity_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(op.f("ix_activities_category"), "activities", ["category"], unique=False)
    op.create_index(op.f("ix_activities_region_code"), "activities", ["region_code"], unique=False)
    op.create_index(op.f("ix_activities_starts_at"), "activities", ["starts_at"], unique=False)
    op.create_table(
        "activity_applications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_applications_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_activity_applications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_applications")),
        sa.UniqueConstraint(
            "activity_id", "user_id", name=op.f("uq_activity_applications_activity_id")
        ),
    )
    op.create_index(
        op.f("ix_activity_applications_activity_id"),
        "activity_applications",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_applications_user_id"), "activity_applications", ["user_id"], unique=False
    )
    op.create_table(
        "activity_likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_activity_likes_activity_id_activities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_activity_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_likes")),
        sa.UniqueConstraint("activity_id", "user_id", name=op.f("uq_activity_likes_activity_id")),
    )
    op.create_index(
        op.f("ix_activity_likes_activity_id"), "activity_likes", ["activity_id"], unique=False
    )
    op.create_index(op.f("ix_activity_likes_user_id"), "activity_likes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_likes_user_id"), table_name="activity_likes")
    op.drop_index(op.f("ix_activity_likes_activity_id"), table_name="activity_likes")
    op.drop_table("activity_likes")
    op.drop_index(op.f("ix_activity_applications_user_id"), table_name="activity_applications")
    op.drop_index(op.f("ix_activity_applications_activity_id"), table_name="activity_applications")
    op.drop_table("activity_applications")
    op.drop_index(op.f("ix_activities_starts_at"), table_name="activities")
    op.drop_index(op.f("ix_activities_region_code"), table_name="activities")
    op.drop_index(op.f("ix_activities_category"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
