"""users approx location

Revision ID: 0601259ca5c9
Revises: cbe0337a0df1
Create Date: 2026-10-02 10:09:14.649651

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0601259ca5c9"
down_revision: str | Sequence[str] | None = "cbe0337a0df1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("geo_lat", sa.Double(), nullable=True))
    op.add_column("users", sa.Column("geo_lng", sa.Double(), nullable=True))
    op.add_column("users", sa.Column("geo_updated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "geo_updated_at")
    op.drop_column("users", "geo_lng")
    op.drop_column("users", "geo_lat")
    # ### end Alembic commands ###
