"""chat rooms messages

Revision ID: d5dda1ecfb28
Revises: c31b760fcc50
Create Date: 2026-10-02 10:14:59.867964

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5dda1ecfb28"
down_revision: str | Sequence[str] | None = "c31b760fcc50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_a_id", sa.Uuid(), nullable=False),
        sa.Column("user_b_id", sa.Uuid(), nullable=False),
        sa.Column("a_last_read_id", sa.BigInteger(), nullable=False),
        sa.Column("b_last_read_id", sa.BigInteger(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("user_a_id < user_b_id", name=op.f("ck_chat_rooms_ordered_pair")),
        sa.ForeignKeyConstraint(
            ["user_a_id"],
            ["users.id"],
            name=op.f("fk_chat_rooms_user_a_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_b_id"],
            ["users.id"],
            name=op.f("fk_chat_rooms_user_b_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_rooms")),
        sa.UniqueConstraint("user_a_id", "user_b_id", name=op.f("uq_chat_rooms_user_a_id")),
    )
    op.create_index(op.f("ix_chat_rooms_user_a_id"), "chat_rooms", ["user_a_id"], unique=False)
    op.create_index(op.f("ix_chat_rooms_user_b_id"), "chat_rooms", ["user_b_id"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audio_key", sa.String(length=64), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('text', 'voice')", name=op.f("ck_chat_messages_kind")),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["chat_rooms.id"],
            name=op.f("fk_chat_messages_room_id_chat_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_chat_messages_sender_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(op.f("ix_chat_messages_room_id"), "chat_messages", ["room_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_room_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_rooms_user_b_id"), table_name="chat_rooms")
    op.drop_index(op.f("ix_chat_rooms_user_a_id"), table_name="chat_rooms")
    op.drop_table("chat_rooms")
    # ### end Alembic commands ###
