"""users intro

Revision ID: cbe0337a0df1
Revises: e36736b374b8
Create Date: 2026-10-02 10:01:06.863514

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbe0337a0df1"
down_revision: str | Sequence[str] | None = "e36736b374b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("intro", sa.String(length=60), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "intro")
    # ### end Alembic commands ###
