"""friend requests

Revision ID: c31b760fcc50
Revises: 0601259ca5c9
Create Date: 2026-10-02 10:10:14.151490

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c31b760fcc50"
down_revision: str | Sequence[str] | None = "0601259ca5c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_user_id", sa.Uuid(), nullable=False),
        sa.Column("to_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'declined')", name=op.f("ck_friend_requests_status")
        ),
        sa.CheckConstraint("from_user_id <> to_user_id", name=op.f("ck_friend_requests_not_self")),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
            name=op.f("fk_friend_requests_from_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_user_id"],
            ["users.id"],
            name=op.f("fk_friend_requests_to_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_friend_requests")),
        sa.UniqueConstraint(
            "from_user_id", "to_user_id", name=op.f("uq_friend_requests_from_user_id")
        ),
    )
    op.create_index(
        op.f("ix_friend_requests_from_user_id"), "friend_requests", ["from_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_friend_requests_to_user_id"), "friend_requests", ["to_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friend_requests_to_user_id"), table_name="friend_requests")
    op.drop_index(op.f("ix_friend_requests_from_user_id"), table_name="friend_requests")
    op.drop_table("friend_requests")
    # ### end Alembic commands ###
